[env]
TERM = "xterm-256color"

[general]
live_config_reload = true

# THEMES
import = [
    "./themes/themes/kanagawa_wave.toml"
]

[window]
option_as_alt = "Both"

[font]
# brew install --cask font-jetbrains-mono-nerd-font
normal = { family = "JetBrainsMono Nerd Font Mono" }
size = 14.0
